# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"4\n\x08position\x12\x0c\n\x04xPos\x18\x02 \x02(\x02\x12\x0c\n\x04yPos\x18\x03 \x02(\x02\x12\x0c\n\x04zPos\x18\x04 \x02(\x02\"4\n\x08velocity\x12\x0c\n\x04xVel\x18\x02 \x02(\x02\x12\x0c\n\x04yVel\x18\x03 \x02(\x02\x12\x0c\n\x04zVel\x18\x04 \x02(\x02\"k\n\x06\x41\x43\x44\x61ta\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x18\n\x05\x61\x63Pos\x18\x02 \x02(\x0b\x32\t.position\x12\x18\n\x05\x61\x63Vel\x18\x03 \x02(\x0b\x32\t.velocity\x12\r\n\x05\x61\x63Rad\x18\x04 \x02(\x02\x12\x10\n\x08\x63ommsUrl\x18\x05 \x02(\t\"\x0b\n\tACListReq\"+\n\nAcListResp\x12\x1d\n\x0c\x61ircraftList\x18\x01 \x03(\x0b\x32\x07.ACData\"8\n\x0b\x41\x63UpdateReq\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1b\n\x08newAcVel\x18\x02 \x02(\x0b\x32\t.velocity\"\x1e\n\x0c\x41\x63UpdateResp\x12\x0e\n\x06status\x18\x01 \x02(\t\"\x1b\n\tAcAddResp\x12\x0e\n\x06status\x18\x01 \x02(\t\"L\n\x0fVisiblityGetReq\x12\x19\n\x06reqPos\x18\x01 \x01(\x0b\x32\t.position\x12\x10\n\x08reqRange\x18\x02 \x01(\x02\x12\x0c\n\x04name\x18\x03 \x01(\t\"A\n\x10VisiblityGetResp\x12\x0e\n\x06status\x18\x01 \x02(\t\x12\x1d\n\x0c\x61ircraftList\x18\x02 \x03(\x0b\x32\x07.ACData\"\x18\n\x08\x41\x63GetReq\x12\x0c\n\x04name\x18\x01 \x02(\t2\xd7\x01\n\tvalidator\x12&\n\tAcGetList\x12\n.ACListReq\x1a\x0b.AcListResp\"\x00\x12,\n\x0b\x41\x63UpdateVel\x12\x0c.AcUpdateReq\x1a\r.AcUpdateResp\"\x00\x12\x1e\n\x05\x41\x63\x41\x64\x64\x12\x07.ACData\x1a\n.AcAddResp\"\x00\x12\x35\n\x0cVisiblityGet\x12\x10.VisiblityGetReq\x1a\x11.VisiblityGetResp\"\x00\x12\x1d\n\x05\x41\x63Get\x12\t.AcGetReq\x1a\x07.ACData\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSITION']._serialized_start=14
  _globals['_POSITION']._serialized_end=66
  _globals['_VELOCITY']._serialized_start=68
  _globals['_VELOCITY']._serialized_end=120
  _globals['_ACDATA']._serialized_start=122
  _globals['_ACDATA']._serialized_end=229
  _globals['_ACLISTREQ']._serialized_start=231
  _globals['_ACLISTREQ']._serialized_end=242
  _globals['_ACLISTRESP']._serialized_start=244
  _globals['_ACLISTRESP']._serialized_end=287
  _globals['_ACUPDATEREQ']._serialized_start=289
  _globals['_ACUPDATEREQ']._serialized_end=345
  _globals['_ACUPDATERESP']._serialized_start=347
  _globals['_ACUPDATERESP']._serialized_end=377
  _globals['_ACADDRESP']._serialized_start=379
  _globals['_ACADDRESP']._serialized_end=406
  _globals['_VISIBLITYGETREQ']._serialized_start=408
  _globals['_VISIBLITYGETREQ']._serialized_end=484
  _globals['_VISIBLITYGETRESP']._serialized_start=486
  _globals['_VISIBLITYGETRESP']._serialized_end=551
  _globals['_ACGETREQ']._serialized_start=553
  _globals['_ACGETREQ']._serialized_end=577
  _globals['_VALIDATOR']._serialized_start=580
  _globals['_VALIDATOR']._serialized_end=795
# @@protoc_insertion_point(module_scope)
